use_default_settings: true

general:
  debug: false
  instance_name: "MyPyRag private web search"

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

server:
  secret_key: "ultrasecretkey"  # Overridden at runtime by SEARXNG_SECRET.
  limiter: false
  image_proxy: false
